title: Ao Collaboration
description: Ao Collaboration
author: Ao Collaboration

navbar-links:
  About: "aboutus"
  Contact: "contact"
#  Resources:
#    - Beautiful Jekyll: "https://beautifuljekyll.com"
#  Author's home: "https://aocollab.tech"

# --- Logo --- #

avatar: "/assets/img/logo_circle.png"
round-avatar: false

# If you want to have an image logo in the top-left corner instead of the title text,
# then specify the following parameter
#title-img: /path/to/image

# --- Footer options --- #

# Select the social network links that you want to show in the footer.
# Uncomment the links you want to show and add your information to each one.
# If you don't want to show a link to an RSS feed, set rss to "false".
social-network-links:
#  telephone: "+64 210 740 420"
email: "kate@aocollab.tech"
#  facebook: kate
#  github: kate
#  twitter: kate
#  rss: true
#  reddit: kate
linkedin: "/company/ao-collaboration-ltd"
#  xing: kate
#  stackoverflow: "5555555/kate"
#  snapchat: kate
#  instagram: kate
#  youtube: user/kate
#  spotify: kate
#  steam: kate
#  twitch: kate
#  yelp: kate
#  telegram: kate
#  calendly: kate

# Select which social network share links to show in posts
share-links-active:
  twitter: false
  facebook: false
  linkedin: true

# How to display the link to your website in the footer
# Remove this if you don't want a link in the footer
#url-pretty: "AoCollab.tech"

# Create a "tags" index page and make tags on each post clickable
link-tags: true

# Excerpt Word Length - Truncates the excerpt to the specified number of words on the index page
excerpt_length: 50

# --- Colours / background image --- #

# blue: "#3287C1"
# light-blue: "#6DCDE9"
# orange: "#F89521"
# light-orange: "#FBB042"
# yellow: "#FCEE23"
navbar-col: "#F5F5F5"
navbar-text-col: "#404040"
navbar-border-col: "#EAEAEA"
page-col: "#FFFFFF"
#link-col: "#008AFF"
link-col: "#3287C1"
#hover-col: "#0085A1"
hover-col: "#F89521"
footer-col: "#F5F5F5"
footer-text-col: "#777777"
footer-link-col: "#404040"

# Alternatively, the navbar, footer, and page background can be set to use background images
#navbar-img: "/assets/img/bgimage.png"
#footer-img: "/assets/img/bgimage.png"
#page-img: "/assets/img/bgimage.png"

# --- Web Statistics Section --- #

# Fill in your Google Analytics gtag.js ID to track your website using gtag
#gtag: ""

# Fill in your Google Analytics ID to track your website using GA
google_analytics: "UA-180185580-1"

# Google Tag Manager ID
#gtm: ""

# --- Comments --- #

# To use Disqus comments, sign up to https://disqus.com and fill in your Disqus shortname (NOT the userid)
#disqus: ""

# To use Facebook Comments, create a Facebook app and fill in the Facebook App ID
#fb_comment_id: ""

# --- Misc --- #

# Character used to separate site title and description in HTML document title
# and RSS feed title
title-separator: "-"

# Ruby Date Format to show dates of posts
date_format: "%-d %B %Y"

# Facebook App ID
#fb_app_id: ""

# --- Other defaults --- #

theme: beautiful-jekyll-theme
timezone: "Pacific/Auckland"
markdown: kramdown
highlighter: rouge
permalink: /:year-:month-:day-:title/
paginate: 5

kramdown:
  input: GFM

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false  # add comments to all blog posts
      social-share: false # add social media sharing buttons to all blog posts
      readtime: true # add estimated reading time on all blog posts
  -
    scope:
      path: "" # all files
    values:
      layout: "page"
      show-avatar: true

# Exclude these files from production site

plugins:
  #  - jekyll-feed
  #  - jekyll-pagiante
  #  - jekyll-sitemap
exclude:
  - CHANGELOG.md
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md

# Beautiful Jekyll / Dean Attali
# 2fc73a3a967e97599c9763d05e564189
